version: '2'

volumes:
  build:
    driver: local
 

services:
  test:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile  
    volumes:
      - build:/build
    links:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: todobackend.settings.test
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      TEST_OUTPUT_DIR: /reports

  builder:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - build:/build
    entrypoint: "entrypoint.sh"
    command: ["pip", "wheel", "--no-index", "-f /build", "."]

  agent:
    image: richardy77/ansible
    links:
      - db
    environment:
      PROBE_HOST: "db"
      PROBE_PORT: "3306"
    command: ["probe.yml"]

  db: 
    image: mysql:5.6
    hostname: db
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: password